"""H11C control-plane catalog: 40 integrators, 45 orchestrators, 40 securities.

These are the agents that bind the specialist roster into a gated cognitive
system. They are not a restatement of L16/L18/L20 taxonomy.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Tuple


@dataclass(frozen=True)
class AgentDef:
    agent_id: str
    family: str
    title: str
    handler: str
    purpose: str
    inputs: Tuple[str, ...]
    outputs: Tuple[str, ...]
    upstream: Tuple[str, ...]
    downstream: Tuple[str, ...]
    params: Dict[str, Any] = field(default_factory=dict)
    failures: Tuple[str, ...] = ()


def _i(suffix, title, handler, purpose, inputs, outputs, up, down, params=None, failures=()):
    return AgentDef(
        f"H11C-{suffix}", "integrator", title, handler, purpose,
        tuple(inputs), tuple(outputs), tuple(up), tuple(down),
        params or {}, tuple(failures),
    )


def _o(suffix, title, handler, purpose, inputs, outputs, up, down, params=None, failures=()):
    return AgentDef(
        f"H11C-{suffix}", "orchestrator", title, handler, purpose,
        tuple(inputs), tuple(outputs), tuple(up), tuple(down),
        params or {}, tuple(failures),
    )


def _s(suffix, title, handler, purpose, inputs, outputs, up, down, params=None, failures=()):
    return AgentDef(
        f"H11C-{suffix}", "security", title, handler, purpose,
        tuple(inputs), tuple(outputs), tuple(up), tuple(down),
        params or {}, tuple(failures),
    )


INTEGRATORS: List[AgentDef] = [
    _i("SCHEMA-BRIDGE", "Schema Bridge", "remap_fields",
       "Maps one agent's output fields onto another's input contract.",
       ["payload", "mapping"], ["payload"], ["H11C-CONTRACT-CHECKER"], ["H11C-PIPELINE-COMPOSER"],
       {"mapping": {"diagnosis": "facts.diagnosis", "vitals": "facts.vitals"}},
       ("Unmapped required keys fail closed.",)),
    _i("EVENT-FUSION", "Event Fusion", "fuse_events",
       "Merges event streams from multiple hops into a single ordered log.",
       ["events"], ["events"], ["H11C-TRACE-JOINER"], ["H11C-OBSERVABILITY-INTEGRATOR"]),
    _i("SUBSTRATE-BINDER", "Substrate Binder", "bind_role",
       "Attaches a case to cognitive-substrate roles (memory, reason, align).",
       ["case"], ["bindings"], [], ["H11C-DOMAIN-BINDER"],
       {"role": "substrate", "targets": ["H11-LONGTERM", "H11-REASON", "H11-ALIGN"]}),
    _i("DOMAIN-BINDER", "Domain Binder", "bind_role",
       "Attaches a case to knowledge-domain specialists.",
       ["case"], ["bindings"], ["H11C-SUBSTRATE-BINDER"], ["H11C-CROSS-DOMAIN-ROUTER"],
       {"role": "domain", "targets": ["H11-ANATOMIA", "H11-PARASITOLOGIA", "H11-PHYSIOLOGIA"]}),
    _i("PIPELINE-COMPOSER", "Pipeline Composer", "compose_pipeline",
       "Compiles a hop list from a goal and the capability map.",
       ["goal", "capabilities"], ["pipeline"], ["H11C-CAPABILITY-MAPPER", "H11C-DEPENDENCY-RESOLVER"], ["H11C-WORKFLOW-ENGINE"]),
    _i("CONTRACT-CHECKER", "Contract Checker", "check_contract",
       "Validates that an envelope payload contains required keys before a hop.",
       ["payload", "required"], ["ok"], ["H11C-SCHEMA-FIREWALL"], ["H11C-TYPE-COERCER"]),
    _i("TYPE-COERCER", "Type Coercer", "coerce_types",
       "Coerces payload fields to declared types (str, float, list).",
       ["payload", "types"], ["payload"], ["H11C-CONTRACT-CHECKER"], ["H11C-SCHEMA-BRIDGE"]),
    _i("TRACE-JOINER", "Trace Joiner", "join_traces",
       "Joins hop traces that share a trace_id into one causal chain.",
       ["traces"], ["trace"], ["H11C-EVENT-FUSION"], ["H11C-TAMPER-EVIDENT"]),
    _i("MEMORY-PROJECTOR", "Memory Projector", "project_memory",
       "Projects composed case state into a LONGTERM-encodable trace.",
       ["payload"], ["trace"], ["H11C-RESULT-REDUCER"], ["H11-LONGTERM"]),
    _i("REASON-INJECTOR", "Reason Injector", "inject_premises",
       "Turns diagnosis and vitals into reasoning premises, not free text.",
       ["payload"], ["premises"], ["H11C-SCHEMA-BRIDGE"], ["H11-REASON"]),
    _i("ALIGN-HOOK", "Align Hook", "attach_align",
       "Forces an ALIGN hop onto any compiled pipeline that would act.",
       ["pipeline"], ["pipeline"], ["H11C-PIPELINE-COMPOSER"], ["H11C-ALIGN-ENFORCE"]),
    _i("PERCEPTION-BINDER", "Perception Binder", "bind_role",
       "Binds L11 perception outputs into the envelope as observations.",
       ["case"], ["bindings"], [], ["H11C-CONTEXT-PACKER"],
       {"role": "perception", "targets": ["H11-VISION", "H11-SPEECH-IN"]}),
    _i("ACTION-BINDER", "Action Binder", "bind_role",
       "Binds L14 agency outputs to licensed tools.",
       ["case"], ["bindings"], ["H11C-ACTION-LICENSE"], ["H11C-TOOL-INTEGRATOR"],
       {"role": "action", "targets": ["H11-TOOLUSE", "H11-FUNCTION-CALL"]}),
    _i("WORLD-BINDER", "World Binder", "bind_role",
       "Binds L12 world-model state to domain dynamics.",
       ["case"], ["bindings"], ["H11C-TEMPORAL-INTEGRATOR"], ["H11C-SCIENCE-INTEGRATOR"],
       {"role": "world", "targets": ["H11-WORLDMODEL", "H11-PREDICT"]}),
    _i("LANGUAGE-BINDER", "Language Binder", "bind_role",
       "Binds NLP extraction into typed envelope fields.",
       ["case"], ["bindings"], [], ["H11C-SCHEMA-BRIDGE"],
       {"role": "language", "targets": ["H11-NLP", "H11-TOKENIZER"]}),
    _i("MEDICAL-INTEGRATOR", "Medical Integrator", "route_domain",
       "Selects the host-infection spine for clinical parasitic cases.",
       ["case"], ["pipeline_id"], ["H11C-CROSS-DOMAIN-ROUTER"], ["H11C-PIPELINE-RUNNER"],
       {"domain": "medical", "pipeline_id": "host_infection"}),
    _i("LEGAL-INTEGRATOR", "Legal Integrator", "route_domain",
       "Routes legal cases to law-domain specialists; does not invent holdings.",
       ["case"], ["pipeline_id"], ["H11C-CROSS-DOMAIN-ROUTER"], ["H11C-HIGH-STAKES"],
       {"domain": "legal", "pipeline_id": "legal_research"}),
    _i("FINANCE-INTEGRATOR", "Finance Integrator", "route_domain",
       "Routes finance cases; never executes trades without ACTION-LICENSE.",
       ["case"], ["pipeline_id"], ["H11C-CROSS-DOMAIN-ROUTER"], ["H11C-HIGH-STAKES"],
       {"domain": "finance", "pipeline_id": "financial_analysis"}),
    _i("ENGINEERING-INTEGRATOR", "Engineering Integrator", "route_domain",
       "Routes engineering design cases onto CS/engineering specialists.",
       ["case"], ["pipeline_id"], ["H11C-CROSS-DOMAIN-ROUTER"], ["H11C-PIPELINE-COMPOSER"],
       {"domain": "engineering", "pipeline_id": "engineering_design"}),
    _i("SCIENCE-INTEGRATOR", "Science Integrator", "route_domain",
       "Routes scientific questions onto world-model and domain science agents.",
       ["case"], ["pipeline_id"], ["H11C-CROSS-DOMAIN-ROUTER"], ["H11C-WORLD-BINDER"],
       {"domain": "science", "pipeline_id": "scientific_model"}),
    _i("CROSS-DOMAIN-ROUTER", "Cross-Domain Router", "route_domain",
       "Classifies a case into medical/legal/finance/engineering/science/general.",
       ["case"], ["domain", "pipeline_id"], ["H11C-ADMISSION-CONTROL"], ["H11C-MEDICAL-INTEGRATOR"]),
    _i("CONTEXT-PACKER", "Context Packer", "pack_context",
       "Packs working-memory slots for the next hop under a token budget.",
       ["payload", "budget"], ["context"], ["H11C-ATTENTION-ALLOCATOR"], ["H11C-PIPELINE-RUNNER"]),
    _i("RESULT-REDUCER", "Result Reducer", "reduce_results",
       "Reduces multi-hop outputs to a single case record.",
       ["payload"], ["summary"], ["H11C-JOIN-BARRIER"], ["H11C-MEMORY-PROJECTOR"]),
    _i("CONFLICT-MERGER", "Conflict Merger", "merge_conflicts",
       "Merges disagreeing specialist outputs by confidence, never by recency alone.",
       ["candidates"], ["chosen"], ["H11C-RESULT-REDUCER"], ["H11C-REASON-INJECTOR"]),
    _i("CAPABILITY-MAPPER", "Capability Mapper", "map_capabilities",
       "Maps a goal string onto required control-plane capabilities.",
       ["goal"], ["capabilities"], [], ["H11C-PIPELINE-COMPOSER"]),
    _i("DEPENDENCY-RESOLVER", "Dependency Resolver", "resolve_deps",
       "Topologically sorts agent ids from declared upstream edges.",
       ["nodes", "edges"], ["order"], ["H11C-GRAPH-INTEGRATOR"], ["H11C-PIPELINE-COMPOSER"]),
    _i("VERSION-ALIGNER", "Version Aligner", "check_contract",
       "Rejects envelopes whose schema_id is not in the accepted set.",
       ["payload"], ["ok"], ["H11C-SCHEMA-FIREWALL"], ["H11C-CONTRACT-CHECKER"],
       {"required": ["schema_id"]}),
    _i("STREAM-INTEGRATOR", "Stream Integrator", "fuse_events",
       "Splices streaming partial envelopes into the case event log.",
       ["events"], ["events"], ["H11C-EVENT-BUS"], ["H11C-TEMPORAL-INTEGRATOR"]),
    _i("BATCH-INTEGRATOR", "Batch Integrator", "reduce_results",
       "Folds a batch of cases into per-case summaries without cross-leak.",
       ["payload"], ["summary"], ["H11C-ISOLATION-DOMAIN"], ["H11C-MULTI-CASE"]),
    _i("HUMAN-INTEGRATOR", "Human Integrator", "splice_external",
       "Splices a human decision into the envelope; never fabricates consent.",
       ["payload", "external"], ["payload"], ["H11C-CONSENT-GATE"], ["H11C-DUAL-CONTROL"],
       {"kind": "human"}),
    _i("TOOL-INTEGRATOR", "Tool Integrator", "splice_external",
       "Splices a tool result only if the tool is on the allowlist.",
       ["payload", "external"], ["payload"], ["H11C-TOOL-ALLOWLIST"], ["H11C-ACTION-BINDER"],
       {"kind": "tool"}),
    _i("CORPUS-INTEGRATOR", "Corpus Integrator", "splice_external",
       "Splices retrieved documents as cited context, not as hidden premises.",
       ["payload", "external"], ["payload"], ["H11C-LANGUAGE-BINDER"], ["H11C-REASON-INJECTOR"],
       {"kind": "corpus"}),
    _i("SENSOR-INTEGRATOR", "Sensor Integrator", "bind_role",
       "Binds sensor packets into perception slots.",
       ["case"], ["bindings"], ["H11C-PERCEPTION-BINDER"], ["H11C-MULTIMODAL-INTEGRATOR"],
       {"role": "sensor", "targets": ["H11-SENSOR"]}),
    _i("ACTUATOR-INTEGRATOR", "Actuator Integrator", "bind_role",
       "Binds licensed actions to embodiment/actuators.",
       ["case"], ["bindings"], ["H11C-ACTION-LICENSE"], ["H11C-ACTION-CYCLE"],
       {"role": "actuator", "targets": ["H11-ACTUATOR"]}),
    _i("ENERGY-INTEGRATOR", "Energy Integrator", "pack_context",
       "Injects energy budget into scheduling context.",
       ["payload"], ["context"], ["H11C-BUDGET-CONTROLLER"], ["H11C-SCHEDULER"],
       {"budget": 32}),
    _i("OBSERVABILITY-INTEGRATOR", "Observability Integrator", "fuse_events",
       "Exports control-plane events to the telemetry log.",
       ["events"], ["events"], ["H11C-EVENT-FUSION"], ["H11C-AUDIT-CHAIN"]),
    _i("MULTIMODAL-INTEGRATOR", "Multimodal Integrator", "fuse_events",
       "Fuses text, numeric, and sensor observations into one event list.",
       ["events"], ["events"], ["H11C-SENSOR-INTEGRATOR", "H11C-LANGUAGE-BINDER"], ["H11C-CONTEXT-PACKER"]),
    _i("TEMPORAL-INTEGRATOR", "Temporal Integrator", "join_traces",
       "Orders hops by timestamp so later hops cannot rewrite earlier ones.",
       ["traces"], ["trace"], ["H11C-TRACE-JOINER"], ["H11C-WORLD-BINDER"]),
    _i("GRAPH-INTEGRATOR", "Graph Integrator", "resolve_deps",
       "Builds the live dependency graph of agents involved in a case.",
       ["nodes", "edges"], ["order"], ["H11C-SPINE-REGISTRAR"], ["H11C-DEPENDENCY-RESOLVER"]),
    _i("SPINE-REGISTRAR", "Spine Registrar", "register_spine",
       "Registers named spines (host_infection, …) as callable pipelines.",
       ["spine_id", "hops"], ["registry"], [], ["H11C-PIPELINE-COMPOSER"],
       {"spine_id": "host_infection",
        "hops": ["H11-ANATOMIA", "H11-PARASITOLOGIA", "H11-PHYSIOLOGIA", "H11-LONGTERM", "H11-REASON", "H11-ALIGN"]}),
]

ORCHESTRATORS: List[AgentDef] = [
    _o("COGNITIVE-LOOP", "Cognitive Loop", "cognitive_tick",
       "Advances the perceive-retrieve-reason-align-act-remember cycle. ACT is illegal before ALIGN.",
       ["state"], ["state"], ["H11C-AGI-KERNEL"], ["H11C-ALIGN-ENFORCE"]),
    _o("GOAL-STACK", "Goal Stack", "goal_stack",
       "Push/pop/peek goals. Nested goals cannot skip the parent's safety gates.",
       ["op", "goal"], ["stack"], ["H11C-NESTED-GOAL"], ["H11C-TASK-DECOMPOSER"]),
    _o("TASK-DECOMPOSER", "Task Decomposer", "goal_stack",
       "Records a decomposition as child goals on the stack, not as untracked side tasks.",
       ["op", "goal"], ["stack"], ["H11C-GOAL-STACK"], ["H11C-PLAN-EXECUTOR"],
       {"op": "push"}),
    _o("SCHEDULER", "Scheduler", "schedule",
       "Priority queue of ready hops. Safety-gated hops outrank speculative ones.",
       ["queue", "item"], ["queue"], ["H11C-BUDGET-CONTROLLER"], ["H11C-ROUTER"]),
    _o("ROUTER", "Router", "route",
       "Routes an envelope to the next agent id in the compiled pipeline.",
       ["pipeline", "index"], ["next_agent"], ["H11C-PIPELINE-COMPOSER"], ["H11C-ZERO-TRUST-HOP"]),
    _o("WORKFLOW-ENGINE", "Workflow Engine", "run_workflow",
       "Executes a DAG of hops, refusing cycles.",
       ["nodes", "edges"], ["order"], ["H11C-DEPENDENCY-RESOLVER"], ["H11C-PIPELINE-RUNNER"]),
    _o("STATE-MACHINE", "State Machine", "state_machine",
       "Case lifecycle: admitted → bound → running → aligned → acted → sealed.",
       ["state", "event"], ["state"], ["H11C-ADMISSION-CONTROL"], ["H11C-COGNITIVE-LOOP"]),
    _o("BLACKBOARD", "Blackboard", "blackboard",
       "Shared working memory with namespaced keys; isolation domains cannot overwrite each other.",
       ["op", "key", "value"], ["board"], ["H11C-ISOLATION-DOMAIN"], ["H11C-CONTEXT-PACKER"]),
    _o("AGENDA", "Agenda", "schedule",
       "Next-action agenda distinct from the long-term goal stack.",
       ["queue", "item"], ["queue"], ["H11C-GOAL-STACK"], ["H11C-ATTENTION-ALLOCATOR"]),
    _o("ATTENTION-ALLOCATOR", "Attention Allocator", "allocate",
       "Allocates the next hop budget to the highest-salience ready agent.",
       ["candidates", "scores"], ["chosen"], ["H11C-AGENDA"], ["H11C-CONTEXT-PACKER"]),
    _o("BUDGET-CONTROLLER", "Budget Controller", "budget",
       "Decrements hop/compute budget; zero budget forces HALT, not silent truncation.",
       ["budget", "cost"], ["budget"], ["H11C-ENERGY-INTEGRATOR"], ["H11C-TIMEOUT-GUARDIAN"]),
    _o("TIMEOUT-GUARDIAN", "Timeout Guardian", "timeout",
       "Marks a hop expired if elapsed exceeds the deadline.",
       ["elapsed", "deadline"], ["expired"], ["H11C-DEADLINE"], ["H11C-FALLBACK"]),
    _o("RETRY", "Retry Orchestrator", "retry",
       "Retries a failed hop with bounded attempts; does not retry HALT.",
       ["attempts", "max_attempts", "halted"], ["retry"], ["H11C-HALT"], ["H11C-FALLBACK"]),
    _o("FALLBACK", "Fallback Orchestrator", "fallback",
       "Switches to a declared fallback pipeline when the primary fails.",
       ["primary_ok", "fallback_id"], ["pipeline_id"], ["H11C-RETRY"], ["H11C-PIPELINE-RUNNER"]),
    _o("PARALLEL-FANOUT", "Parallel Fanout", "fanout",
       "Duplicates an envelope to N workers with isolated blackboards.",
       ["n"], ["branches"], ["H11C-WORKER-POOL"], ["H11C-JOIN-BARRIER"]),
    _o("JOIN-BARRIER", "Join Barrier", "join",
       "Joins fanout branches; incomplete sets do not pass.",
       ["branches", "expected"], ["joined"], ["H11C-PARALLEL-FANOUT"], ["H11C-RESULT-REDUCER"]),
    _o("PREEMPTOR", "Preemptor", "preempt",
       "Preempts a running hop for a higher-priority safety interrupt.",
       ["running", "incoming_priority"], ["preempt"], ["H11C-INTERRUPT-HANDLER"], ["H11C-SCHEDULER"]),
    _o("PRIORITY-INVERSION", "Priority Inversion Fix", "preempt",
       "Boosts a low-priority holder of a safety lock so the high-priority waiter is not starved.",
       ["running", "incoming_priority"], ["preempt"], ["H11C-PREEMPTOR"], ["H11C-SCHEDULER"],
       {"boost": True}),
    _o("LOAD-SHEDDER", "Load Shedder", "budget",
       "Drops lowest-priority speculative hops when budget is critical.",
       ["budget", "cost"], ["budget"], ["H11C-BUDGET-CONTROLLER"], ["H11C-SCHEDULER"],
       {"shed": True}),
    _o("SESSION", "Session Orchestrator", "blackboard",
       "Session-scoped blackboard that dies with the session token.",
       ["op", "key", "value"], ["board"], ["H11C-SESSION-BOUND"], ["H11C-BLACKBOARD"],
       {"namespace": "session"}),
    _o("PLAN-EXECUTOR", "Plan Executor", "run_workflow",
       "Executes an ordered plan; each step is a routed hop.",
       ["nodes", "edges"], ["order"], ["H11C-TASK-DECOMPOSER"], ["H11C-ROUTER"]),
    _o("REPLANNER", "Replanner", "cognitive_tick",
       "Forces the loop back to REASON after ALIGN says REPLAN.",
       ["state"], ["state"], ["H11C-ALIGN-ENFORCE"], ["H11C-COGNITIVE-LOOP"],
       {"force_phase": "REASON"}),
    _o("INTERRUPT-HANDLER", "Interrupt Handler", "preempt",
       "Handles kill-switch and emergency-stop as non-maskable interrupts.",
       ["running", "incoming_priority"], ["preempt"], ["H11C-EMERGENCY-STOP"], ["H11C-HALT"],
       {"nmi": True}),
    _o("META-CONTROLLER", "Meta Controller", "allocate",
       "Chooses which orchestrator owns the next tick.",
       ["candidates", "scores"], ["chosen"], ["H11C-AGI-KERNEL"], ["H11C-COGNITIVE-LOOP"]),
    _o("PERCEPTION-CYCLE", "Perception Cycle", "cognitive_tick",
       "Runs one perception phase of the cognitive loop.",
       ["state"], ["state"], ["H11C-PERCEPTION-BINDER"], ["H11C-COGNITIVE-LOOP"],
       {"force_phase": "PERCEIVE"}),
    _o("DELIBERATION-CYCLE", "Deliberation Cycle", "cognitive_tick",
       "Runs retrieve+reason phases.",
       ["state"], ["state"], ["H11C-REASON-INJECTOR"], ["H11C-COGNITIVE-LOOP"],
       {"force_phase": "REASON"}),
    _o("ACTION-CYCLE", "Action Cycle", "cognitive_tick",
       "Runs the act phase only if ALIGN allowed the trajectory.",
       ["state"], ["state"], ["H11C-ALIGN-ENFORCE"], ["H11C-ACTION-LICENSE"],
       {"force_phase": "ACT"}),
    _o("REFLECTION-CYCLE", "Reflection Cycle", "cognitive_tick",
       "Post-action reflection before memory write.",
       ["state"], ["state"], ["H11C-ACTION-CYCLE"], ["H11C-SLEEP-CYCLE"],
       {"force_phase": "REMEMBER"}),
    _o("SLEEP-CYCLE", "Sleep Cycle", "cognitive_tick",
       "Triggers LONGTERM consolidation; no new ACT during sleep.",
       ["state"], ["state"], ["H11C-MEMORY-PROJECTOR"], ["H11C-COGNITIVE-LOOP"],
       {"force_phase": "REMEMBER", "sleep": True}),
    _o("CURIOSITY-DRIVER", "Curiosity Driver", "goal_stack",
       "Pushes an epistemic goal only when budget remains after safety hops.",
       ["op", "goal"], ["stack"], ["H11C-BUDGET-CONTROLLER"], ["H11C-GOAL-STACK"],
       {"op": "push", "kind": "epistemic"}),
    _o("INTERRUPTIBLE-LOOP", "Interruptible Loop", "cognitive_tick",
       "Cognitive loop variant that yields after each phase for NMI checks.",
       ["state"], ["state"], ["H11C-INTERRUPT-HANDLER"], ["H11C-COGNITIVE-LOOP"],
       {"yield_each_phase": True}),
    _o("NESTED-GOAL", "Nested Goal Orchestrator", "goal_stack",
       "Child goals inherit parent compartments and licenses.",
       ["op", "goal"], ["stack"], ["H11C-GOAL-STACK"], ["H11C-COMPARTMENT"]),
    _o("MULTI-CASE", "Multi-Case Orchestrator", "fanout",
       "Runs isolated cases in parallel without blackboard crossover.",
       ["n"], ["branches"], ["H11C-ISOLATION-DOMAIN"], ["H11C-JOIN-BARRIER"]),
    _o("CONSENSUS", "Consensus Orchestrator", "join",
       "Requires N-of-M specialist agreement before ALIGN sees a fact.",
       ["branches", "expected"], ["joined"], ["H11C-CONFLICT-MERGER"], ["H11C-ALIGN-HOOK"]),
    _o("DEBATE", "Debate Orchestrator", "merge_conflicts",
       "Structured disagreement: retains minority report alongside the winner.",
       ["candidates"], ["chosen"], ["H11C-CONFLICT-MERGER"], ["H11C-REASON-INJECTOR"],
       {"keep_minority": True}),
    _o("SUPERVISOR", "Supervisor Orchestrator", "allocate",
       "Supervises worker hops; can only HALT or REPLAN, never skip ALIGN.",
       ["candidates", "scores"], ["chosen"], ["H11C-WORKER-POOL"], ["H11C-HALT"]),
    _o("WORKER-POOL", "Worker Pool", "fanout",
       "Pool of identical workers for fanout hops.",
       ["n"], ["branches"], ["H11C-SCHEDULER"], ["H11C-PARALLEL-FANOUT"]),
    _o("EVENT-BUS", "Event Bus", "fuse_events",
       "In-process pub/sub for control-plane events.",
       ["events"], ["events"], ["H11C-OBSERVABILITY-INTEGRATOR"], ["H11C-STREAM-INTEGRATOR"]),
    _o("DEADLINE", "Deadline Scheduler", "timeout",
       "Attaches absolute deadlines to hops.",
       ["elapsed", "deadline"], ["expired"], ["H11C-SCHEDULER"], ["H11C-TIMEOUT-GUARDIAN"]),
    _o("MODE-SWITCH", "Cognitive Mode Switch", "state_machine",
       "Switches fast/slow thinking modes; slow mode is mandatory for medical/legal.",
       ["state", "event"], ["state"], ["H11C-HIGH-STAKES"], ["H11C-COGNITIVE-LOOP"],
       {"modes": ["fast", "slow"]}),
    _o("HALT", "Halt Orchestrator", "halt",
       "Seals the case. No further ACT. Resume requires a new admission.",
       ["state"], ["state"], ["H11C-KILL-SWITCH", "H11C-EMERGENCY-STOP"], ["H11C-AUDIT-CHAIN"]),
    _o("RESUME", "Resume Orchestrator", "resume",
       "Resumes only from a checkpoint after a fresh ADMISSION-CONTROL pass.",
       ["checkpoint", "admitted"], ["state"], ["H11C-CHECKPOINT", "H11C-ADMISSION-CONTROL"], ["H11C-COGNITIVE-LOOP"]),
    _o("CHECKPOINT", "Checkpoint Orchestrator", "checkpoint",
       "Snapshots blackboard + pipeline index; snapshots are MAC'd.",
       ["state"], ["checkpoint"], ["H11C-INTEGRITY-MAC"], ["H11C-RESUME"]),
    _o("PIPELINE-RUNNER", "Pipeline Runner", "run_pipeline",
       "Runs a registered spine hop-by-hop under zero-trust and ALIGN-enforce.",
       ["pipeline_id", "payload"], ["payload"], ["H11C-SPINE-REGISTRAR", "H11C-ZERO-TRUST-HOP"], ["H11C-ALIGN-ENFORCE"]),
    _o("AGI-KERNEL", "AGI Kernel", "agi_tick",
       "Top-level tick: admit, bind, compose, run, align-enforce, remember, seal.",
       ["case"], ["result"], ["H11C-ADMISSION-CONTROL"], ["H11C-COGNITIVE-LOOP"]),
]

SECURITIES: List[AgentDef] = [
    _s("IDENTITY", "Identity", "identity",
       "Issues a stable agent/case identity. No hop without an identity.",
       ["name"], ["identity"], [], ["H11C-CAPABILITY-TOKEN"]),
    _s("CAPABILITY-TOKEN", "Capability Token", "capability",
       "Mints HMAC-style capability tokens. Scopes are explicit; absence is deny.",
       ["identity", "scopes"], ["token"], ["H11C-IDENTITY"], ["H11C-LEAST-PRIVILEGE"]),
    _s("SANDBOX-GATE", "Sandbox Gate", "sandbox",
       "Marks a hop sandboxed. Unsandboxed ACT is refused.",
       ["hop"], ["sandboxed"], ["H11C-ISOLATION-DOMAIN"], ["H11C-ACTION-LICENSE"]),
    _s("ENVELOPE-AUTH", "Envelope Auth", "capability",
       "Authenticates the envelope bearer token before routing.",
       ["identity", "scopes"], ["token"], ["H11C-CAPABILITY-TOKEN"], ["H11C-ZERO-TRUST-HOP"]),
    _s("SCHEMA-FIREWALL", "Schema Firewall", "check_contract",
       "Drops envelopes that do not match the declared schema_id.",
       ["payload"], ["ok"], ["H11C-VERSION-ALIGNER"], ["H11C-CONTRACT-CHECKER"],
       {"required": ["schema_id"]}),
    _s("INJECTION-GATE", "Injection Gate", "injection",
       "Rejects payloads containing instruction-override markers in user fields.",
       ["text"], ["clean"], [], ["H11C-INPUT-SANITIZER"]),
    _s("TOOL-ALLOWLIST", "Tool Allowlist", "allowlist",
       "Permits only named tools. Unknown tool ids fail closed.",
       ["item", "allowed"], ["ok"], [], ["H11C-TOOL-INTEGRATOR"]),
    _s("DATA-CLASS", "Data Classification", "classify",
       "Labels payload as public/internal/medical/secret. Medical cannot flow to public sinks.",
       ["payload"], ["label"], [], ["H11C-COMPARTMENT"]),
    _s("COMPARTMENT", "Compartment", "compartment",
       "Enforces domain compartments. Medical facts do not enter finance pipelines.",
       ["label", "sink"], ["ok"], ["H11C-DATA-CLASS"], ["H11C-ISOLATION-DOMAIN"]),
    _s("AUDIT-CHAIN", "Audit Chain", "audit",
       "Append-only hash chain of control-plane events. Breaks are detectable.",
       ["event"], ["head"], [], ["H11C-TAMPER-EVIDENT"]),
    _s("RATE-LIMIT", "Rate Limit", "rate_limit",
       "Token bucket per identity. Exhaustion is HALT of that identity's ACT, not silent drop of ALIGN.",
       ["identity", "tokens"], ["ok"], ["H11C-IDENTITY"], ["H11C-ADMISSION-CONTROL"]),
    _s("PRIVILEGE-DROP", "Privilege Drop", "privilege",
       "Drops scopes after a hop. Scopes never increase mid-case.",
       ["scopes", "drop"], ["scopes"], ["H11C-CAPABILITY-TOKEN"], ["H11C-LEAST-PRIVILEGE"]),
    _s("OUTPUT-REDACTOR", "Output Redactor", "redact",
       "Redacts secret-class fields from externally emitted payloads.",
       ["payload", "keys"], ["payload"], ["H11C-DATA-CLASS"], ["H11C-EXFIL-GUARD"]),
    _s("INPUT-SANITIZER", "Input Sanitizer", "sanitize",
       "Strips control characters and wrapper tags from user strings.",
       ["text"], ["text"], ["H11C-INJECTION-GATE"], ["H11C-SCHEMA-BRIDGE"]),
    _s("POLICY-ENGINE", "Policy Engine", "policy",
       "Evaluates named rules (allow/deny) over envelope attributes.",
       ["rules", "attrs"], ["decision"], ["H11C-LEAST-PRIVILEGE"], ["H11C-ACTION-LICENSE"]),
    _s("CONSENT-GATE", "Consent Gate", "consent",
       "Requires an explicit consent flag for human-impacting ACT. Absence is deny.",
       ["consent"], ["ok"], ["H11C-HUMAN-INTEGRATOR"], ["H11C-DUAL-CONTROL"]),
    _s("KILL-SWITCH", "Kill Switch", "halt",
       "Global halt. Latches until operator resume.",
       ["state"], ["state"], [], ["H11C-EMERGENCY-STOP"]),
    _s("DUAL-CONTROL", "Dual Control", "dual",
       "High-stakes ACT requires two independent approvals.",
       ["approvals", "need"], ["ok"], ["H11C-HIGH-STAKES"], ["H11C-ACTION-LICENSE"]),
    _s("PROVENANCE-SEAL", "Provenance Seal", "mac",
       "Seals payload provenance so later hops cannot rewrite source identity.",
       ["payload"], ["mac"], ["H11C-IDENTITY"], ["H11C-TAMPER-EVIDENT"]),
    _s("INTEGRITY-MAC", "Integrity MAC", "mac",
       "Message authentication of checkpoints and envelopes.",
       ["payload"], ["mac"], ["H11C-CAPABILITY-TOKEN"], ["H11C-CHECKPOINT"]),
    _s("REPLAY-GUARD", "Replay Guard", "replay",
       "Rejects envelopes whose nonce was already seen.",
       ["nonce"], ["ok"], ["H11C-ENVELOPE-AUTH"], ["H11C-ZERO-TRUST-HOP"]),
    _s("CONFUSED-DEPUTY", "Confused Deputy Guard", "privilege",
       "Prevents a low-privilege hop from wielding a higher-privilege token.",
       ["scopes", "drop"], ["scopes"], ["H11C-CAPABILITY-TOKEN"], ["H11C-DELEGATION-LIMIT"]),
    _s("DELEGATION-LIMIT", "Delegation Limit", "privilege",
       "Caps how far a capability may be delegated.",
       ["scopes", "drop"], ["scopes"], ["H11C-CONFUSED-DEPUTY"], ["H11C-LEAST-PRIVILEGE"],
       {"max_depth": 2}),
    _s("SECRET-VAULT", "Secret Vault", "vault",
       "Stores secrets by id. Process never returns the secret in the envelope.",
       ["op", "key", "value"], ["ok"], [], ["H11C-OUTPUT-REDACTOR"]),
    _s("ISOLATION-DOMAIN", "Isolation Domain", "compartment",
       "Hard partition of blackboard namespaces per case.",
       ["label", "sink"], ["ok"], ["H11C-COMPARTMENT"], ["H11C-BLACKBOARD"]),
    _s("MEDICAL-SAFETY", "Medical Safety Gate", "policy",
       "Medical ACT requires confidence ≥ threshold and ALIGN allowed.",
       ["rules", "attrs"], ["decision"], ["H11C-ALIGN-ENFORCE"], ["H11C-ACTION-LICENSE"],
       {"rules": [{"when": "medical", "require": ["align_allowed", "confidence"]}]}),
    _s("HIGH-STAKES", "High-Stakes Gate", "dual",
       "Legal, medical, and financial ACT are high-stakes by default.",
       ["approvals", "need"], ["ok"], ["H11C-MODE-SWITCH"], ["H11C-DUAL-CONTROL"],
       {"need": 2}),
    _s("EXFIL-GUARD", "Exfil Guard", "redact",
       "Blocks secret and medical fields from leaving the compartment.",
       ["payload", "keys"], ["payload"], ["H11C-DATA-CLASS"], ["H11C-OUTPUT-REDACTOR"],
       {"keys": ["secret", "medical_record"]}),
    _s("MODEL-INTEGRITY", "Model Integrity", "mac",
       "Pins specialist module hashes before a hop.",
       ["payload"], ["mac"], ["H11C-SUPPLY-CHAIN-PIN"], ["H11C-ZERO-TRUST-HOP"]),
    _s("SUPPLY-CHAIN-PIN", "Supply Chain Pin", "allowlist",
       "Only pinned agent ids may run. Unknown agent.py paths fail closed.",
       ["item", "allowed"], ["ok"], [], ["H11C-MODEL-INTEGRITY"]),
    _s("SESSION-BOUND", "Session Bound", "replay",
       "Binds tokens to a session nonce so they cannot be replayed across sessions.",
       ["nonce"], ["ok"], ["H11C-IDENTITY"], ["H11C-CAPABILITY-TOKEN"]),
    _s("LEAST-PRIVILEGE", "Least Privilege", "privilege",
       "Intersects requested scopes with the hop's declared minimum.",
       ["scopes", "drop"], ["scopes"], ["H11C-CAPABILITY-TOKEN"], ["H11C-ACTION-LICENSE"]),
    _s("ZERO-TRUST-HOP", "Zero-Trust Hop", "zero_trust",
       "Re-verifies identity, token, sandbox, and schema on every hop.",
       ["identity", "token", "sandboxed", "schema_ok"], ["ok"],
       ["H11C-IDENTITY", "H11C-CAPABILITY-TOKEN", "H11C-SANDBOX-GATE"], ["H11C-ROUTER"]),
    _s("TAMPER-EVIDENT", "Tamper-Evident Trace", "audit",
       "Verifies the audit chain head matches the last sealed event.",
       ["event"], ["head"], ["H11C-AUDIT-CHAIN"], ["H11C-WITNESS-LOG"]),
    _s("EMERGENCY-STOP", "Emergency Stop", "halt",
       "Immediate halt plus kill-switch latch.",
       ["state"], ["state"], ["H11C-KILL-SWITCH"], ["H11C-HALT"]),
    _s("ALIGN-ENFORCE", "Align Enforce", "align_enforce",
       "No ACT unless ALIGN has allowed this trace_id. Skipping ALIGN is a halt.",
       ["trace_id", "align_allowed", "would_act"], ["ok"], ["H11-ALIGN"], ["H11C-ACTION-CYCLE"]),
    _s("ACTION-LICENSE", "Action License", "license",
       "Issues a one-hop ACT license only when align_enforce, sandbox, and policy pass.",
       ["ok_flags"], ["licensed"], ["H11C-ALIGN-ENFORCE", "H11C-SANDBOX-GATE", "H11C-POLICY-ENGINE"], ["H11C-ACTION-BINDER"]),
    _s("WITNESS-LOG", "Witness Log", "audit",
       "Externalizable witness of sealed hops for later audit.",
       ["event"], ["head"], ["H11C-TAMPER-EVIDENT"], ["H11C-AUDIT-CHAIN"]),
    _s("QUARANTINE", "Quarantine", "halt",
       "Quarantines a case: no ACT, no external emit, memory write allowed.",
       ["state"], ["state"], ["H11C-INJECTION-GATE"], ["H11C-HALT"],
       {"quarantine": True}),
    _s("ADMISSION-CONTROL", "Admission Control", "admit",
       "First gate. Unadmitted cases never reach PIPELINE-RUNNER.",
       ["case"], ["admitted"], [], ["H11C-IDENTITY", "H11C-AGI-KERNEL"]),
]


AGENTS: List[AgentDef] = INTEGRATORS + ORCHESTRATORS + SECURITIES
BY_ID = {a.agent_id: a for a in AGENTS}


def family_counts() -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for a in AGENTS:
        counts[a.family] = counts.get(a.family, 0) + 1
    return counts
